### PR TITLE
Add RTL support

### PR DESCRIPTION
**Pull request by AliRezaBeigy**
Add RTL support
Update dependencies
Remove deprecated dependencies
Create new example project with react native 0.63
Add option to subtract status bar height from display and y axle of touch event
Fix main file in package.json
Update gitignore
Remove yarn.lock

### CODE REVIEW

**Comment by doomsower** [comment]
Wow, that's a lot of changes. I will build and check it this weekend. Thank you.

**Comment by doomsower** [comment]
I got lost in multiple changes that are related to tooling, code style and example updates.
So I've modernized project myself, and also added CI.

Please add these features:
- RTL support
- Add option to subtract status bar height from display and y axle of touch event

in separate pull requests. Also, please update readme if necessary.

**Comment by filipef101** [comment]
Still doesn't work on latest version btw

**Comment by filipef101** [comment]
Patch that works
[react-native-modal-popover+1.0.0.txt](https://github.com/doomsower/react-native-modal-popover/files/5886736/react-native-modal-popover%2B1.0.0.txt)

**Comment by filipef101** [comment]
The animation still starts from the wrong place tough, but better than nothing

**Comment by filipef101** [comment]
[Patch with animations fixed](https://github.com/doomsower/react-native-modal-popover/files/5886840/react-native-modal-popover%2B1.0.0.txt)

**Pull request closed without merging**
